# <b><font color='rebeccapurple'>Practicum 13_light</font></b>

### <font color='rebeccapurple'>Задача 1</font>

Создайте диаграмму рассеяния для визуализации взаимосвязи между двумя переменными. Используйте набор данных tips, доступный в Plotly Express. Постройте график total_bill на оси x и tip на оси y. Раскрасьте точки по времени (обед или ужин).

In [1]:
import plotly.express as px
import pandas as pd

In [2]:
df_tips = px.data.tips()
df_tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
fig = px.scatter(data_frame = df_tips,
              x = 'total_bill',
              y = 'tip',
              color = 'time',
              trendline= 'ols',
              title = 'Total Bill vs Tip by Time of Day',)
fig.show()

### <font color='rebeccapurple'>Задача 2</font>

Создайте box plot для анализа распределения переменной. Используйте набор данных tips. Создайте box plot для total_bill. Разделите данные по дням, чтобы увидеть распределение для каждого дня.

In [12]:
fig = px.box(data_frame = df_tips,
              y = 'total_bill',
              x= 'day',
              category_orders={'day': ['Thur', 'Fri', 'Sat', 'Sun']},
              title = 'Total Bill Distribution by Day of Week')
              
fig.show()

### <font color='rebeccapurple'>Задача 3</font>

Создайте гистограмму, чтобы понять распределение частот переменной. Используйте набор данных tips. Создайте гистограмму для total_bill. Установите число бинов равным 20.

In [40]:
line=dict(
color='darkgray', # Border color
width=1 # Border width in pixels
)

In [49]:
fig = px.histogram(data_frame = df_tips,
                   x = 'total_bill',

                   title = 'Distribution of Total Bills',
                   color_discrete_sequence=['teal'],
                   width = 900,
                   height = 600
                   )

fig.update_traces(marker=dict(line=dict(color='black', width=1)))
fig.show()

### <font color='rebeccapurple'>Задача 4</font>

Создайте линейный график для наблюдения тенденций за определенный период. Используйте набор данных gapminder, доступный в Plotly Express. Отметьте год на оси x и lifeExp на оси y. Отфильтруйте данные, чтобы включить в них только Германию.

In [11]:
df_gapminder = px.data.gapminder()
df_gapminder

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [94]:
from plotly.subplots import make_subplots
df_Germany = df_gapminder.query("country == 'Germany'")
fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(
    px.line(data_frame=df_Germany,
            x='year',
            y='lifeExp',
            markers=True,
            color_discrete_sequence=['green']).data[0],
    secondary_y=False
)

fig.add_trace(
    px.line(data_frame=df_Germany,
            x='year',
            y='gdpPercap',
            markers=True,
            color_discrete_sequence=['red']).data[0],
    secondary_y=True
)

# Имена для легенды
fig.data[0].name = 'Life Expectancy'
fig.data[1].name = 'GDP per Capita'
fig.data[0].showlegend = True
fig.data[1].showlegend = True

# Подписи осей
fig.update_yaxes(title_text='Life Expectancy (years)', secondary_y=False)
fig.update_yaxes(title_text='GDP per Capita (USD)', secondary_y=True)
fig.update_xaxes(title_text='Year')

fig.update_layout(
    title='Life Expectancy and GDP per Capita in Germany Over Time',
    legend=dict(x=0.01, y=0.99)
)

fig.show()

### <font color='rebeccapurple'>Задача 5</font>

Создайте круговую диаграмму для анализа соотношения категорий. Используйте набор данных tips. Создайте круговую диаграмму, показывающую долю общих счетов по дням.

In [80]:
fig = px.pie(data_frame = df_tips,
             names='day',
             values='total_bill',
             hole = 0.4,
             category_orders={'day': ['Thur', 'Fri', 'Sat', 'Sun']},
             title='Total Bill Distribution by Day of Week',
             width=700,
             height=500,)
fig.update_traces( # обновить данные объектов
    textinfo = 'value+label', # Как подписать данные на диаграмме
    pull = [0, 0, 0, 0.2] # Выделение отдельного кусочка пирога
)             
fig.show()

### <font color='rebeccapurple'>Задача 6</font>

Создайте тепловую карту для визуализации корреляции между несколькими переменными. Используйте набор данных iris, доступный в Plotly Express. Рассчитайте корреляционную матрицу и визуализируйте ее с помощью тепловой карты.

In [22]:
df_iris = px.data.iris()
df_iris.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [87]:
iris_correlation = df_iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species_id']].corr()
iris_correlation

              sepal_length  sepal_width  petal_length  petal_width  species_id
sepal_length      1.000000    -0.109369      0.871754     0.817954    0.782561
sepal_width      -0.109369     1.000000     -0.420516    -0.356544   -0.419446
petal_length      0.871754    -0.420516      1.000000     0.962757    0.949043
petal_width       0.817954    -0.356544      0.962757     1.000000    0.956464
species_id        0.782561    -0.419446      0.949043     0.956464    1.000000

In [93]:
fig = px.imshow(iris_correlation,
                text_auto=True,
                color_continuous_scale='tempo',
                title='Correlation Matrix of Iris Dataset',
                width=700,
                height=500
                )
fig.show()