# <b><font color='saddlebrown'>Основы корреляции</font></b>

In [1]:
# Импорт библиотек
import pandas as pd
from scipy.stats import pearsonr, spearmanr
import seaborn as sns
from sklearn.datasets import load_wine

### <b><font color='saddlebrown'>1. Коэффициент корреляции Пирсона</font></b>
Функция pearsonr из библиотеки scipy.stats возвращает:
- r - Коэффициент корреляции Пирсона (от –1 до +1)
- p_value - p-значение для проверки гипотезы H0 (p = 0, значит, линейная связь есть)

Рассчитайте коэффициент корреляции Пирсона между длиной и шириной лепестка в наборе данных Iris.

In [2]:
# Запишем в DataFrame df_iris данные из датасета Iris
df_iris = sns.load_dataset('iris')
df_iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
# В переменные corr, p_value запишем результат работы функции pearsonr
corr, p_value = pearsonr(df_iris['petal_length'], df_iris['petal_width'])

In [4]:
# Выведем результат и интерпретируем его
print(corr)
print(p_value)

0.962865431402796
4.6750039073286175e-86

### <b><font color='saddlebrown'>2. Коэффициент корреляции Спирмена</font></b>
Функция spearmanr из библиотеки scipy.stats возвращает:
- rho - коэффициент ранговой корреляции Спирмена (от –1 до +1)
- p_value - p-значение для проверки гипотезы H0 (p = 0, значит, монотонная связь есть)

Рассчитайте коэффициент корреляции Спирмена между содержанием color_intensity и hue в наборе данных Wine Quality.

In [5]:
# Запишем в DataFrame df_wine данные из датасета wine
wine_data = load_wine()
df_wine = pd.DataFrame(data = wine_data.data, columns = wine_data.feature_names)
df_wine['target'] = wine_data.target
df_wine

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [6]:
# В переменные corr, p_value запишем результат работы функции spearmanr
corr, p_value = spearmanr(df_wine['color_intensity'], df_wine['hue'])

In [7]:
# Выведем результат и интерпретируем его
print(corr)
print(p_value)

-0.4185217619000421
6.117037530987142e-09