# <b><font color='rebeccapurple'>Plotly. Введение и базовые графики</font></b>

Ссылка на документацию [Plotly](https://plotly.com/python-api-reference/plotly.express.html)

### <font color='rebeccapurple'>1. Начало работы с Plotly</font>

##### <font color='rebeccapurple'>1.1. Установка необходимых библиотек</font>

In [1]:
# Установка библиотеки Plotly
!pip install plotly

Collecting plotly
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.21.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: packaging in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from plotly) (26.1)
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------------ --------------------------- 3.1/9.9 MB 34.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 51.1 MB/s  0:00:00
Downloading narwhals-2.21.0-py3-none-any.whl (451 kB)
Installing collected packages: narwhals, plotly

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   ---------------------------------------- 2/2 [plotly]

Successfully installed narwhals-2.21.0 plotly-6.7.0

In [2]:
# Установка ipywidgets
!pip install ipywidgets

Requirement already satisfied: ipywidgets in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (8.1.8)
Requirement already satisfied: comm>=0.1.3 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipywidgets) (9.12.0)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: executing>=1.2.0 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)

In [3]:
import plotly.express as px

##### <font color='rebeccapurple'>1.2. Пример создания базового линейного графика</font>

In [4]:
data = {'x': [1, 2, 3, 4, 5], 'y': [4, 1, 8, 3, 10]}
fig = px.line(data, x = 'x', y = 'y', title = 'Простой линейный график')
fig.show()

### <font color='rebeccapurple'>2. Line Chart</font>

In [5]:
import pandas as pd

df_finance = pd.read_csv('../data/finance_chart_apple.csv')
df_finance.head(3)

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing

In [6]:
# Первый аргумент - датафрейм
# x - название столбца для отображения данных по оси X
# y - название столбца для отображения данных по оси Y
# title - название графика
fig = px.line(data_frame = df_finance,
              x = 'Date',
              y = 'AAPL.Close',
              title = 'AAPL.Close Trend Over Days'
              )
fig.show()

In [7]:
# добавим деление по признаку Direction
fig = px.line(data_frame = df_finance,
              x = 'Date', 
              y = 'AAPL.Close', 
              line_group = 'direction',
              color = 'direction',
              title = 'Total AAPL.Close Trend by Direction'
             )
fig.show()

In [60]:
# Другие параметры
fig = px.line(data_frame = df_finance,
              x = 'Date', 
              y = 'AAPL.Close',
              line_group = 'direction',
              color = 'direction',
              title = 'Total AAPL.Close Trend by Direction',
              # markers = True, # Показывать/не показывать маркеры на линии
              # line_dash = 'direction', # сопоставить тип линии с полем direction
              # symbol = 'direction', # сопоставить тип символа с полем direction
              # text = 'AAPL.Close', # какое поля взять для подписи данных на графике
              labels = {'Date':'Дата', 'AAPL.Close':'Цена закрытия акций'},
              color_discrete_sequence = ['green', 'black'],
              line_shape = 'linear' # тип линии 'linear', 'spline', 'hv', 'vh', 'hvh', 'vhv'
             )
fig.show()

In [9]:
# Матрица линейных графиков
fig = px.line(data_frame = df_finance,
              x = 'Date', 
              y = 'AAPL.Close',
              # line_group = 'direction',
              # color = 'direction',
              title = 'Total AAPL.Close Trend by Direction',
              # markers = True, # Показывать/не показывать маркеры на линии
              # line_dash = 'direction', # сопоставить тип линии с полем direction
              # symbol = 'direction', # сопоставить тип символа с полем direction
              # text = 'AAPL.Close', # какое поля взять для подписи данных на графике
              labels = {'Date':'Дата', 'AAPL.Close':'Цена закрытия акций'},
              facet_row = 'direction'
             )
fig.show()

### <font color='rebeccapurple'>3. Наборы данных, встроенные в PlotlyExpress</font>
[Datasets](https://plotly.com/python-api-reference/generated/plotly.data.html)

In [61]:
df_gapminder = px.data.gapminder()
df_gapminder

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [11]:
df_Germany = px.data.gapminder().query('country == "Germany"') # Внешние и внутренние кавычки - разные
df_Germany.head(5)

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
564,Germany,Europe,1952,67.5,69145952,7144.114393,DEU,276
565,Germany,Europe,1957,69.1,71019069,10187.826650,DEU,276
566,Germany,Europe,1962,70.3,73739117,12902.462910,DEU,276
567,Germany,Europe,1967,70.8,76368453,14745.625610,DEU,276
568,Germany,Europe,1972,71.0,78717088,18016.180270,DEU,276

### <font color='rebeccapurple'>4. Bar Charts</font>

In [ ]:
df_Germany = px.data.gapminder().query("country=='Germany'") 
df_Germany['popMillion'] = df_Germany['pop']/1_000_000

fig = px.bar(data_frame = df_Germany, 
             x = 'year', # значения из какого столбца таблицы на оси X
             y = 'popMillion', # значения из какого столбца таблицы на оси Y
             title = 'Total Population of Germany by Year') # заголовок диаграммы
fig.show()

In [13]:
fig = px.bar(data_frame = df_Germany, 
             x = 'year',
             y = ['popMillion', 'lifeExp'], # Несколько значений по столбцу Y
             title = 'Total Population of Germany by Year',
             barmode = 'group' # способ расположения нескольких столбцов:'group', 'overlay', 'relative' 
)
fig.show()

In [14]:
# другие параметры
fig = px.bar(data_frame = df_Germany, 
             x = 'year',
             y = 'popMillion',
             title = 'Total Population of Germany by Year',
             color = 'lifeExp',
             text = round(df_Germany['popMillion'], 1), # Подписи столбцов
             # text_auto = True,
             labels = {'year':'Год', 'popMillion':'Население (млн.)'}, # Подписи осей
             orientation = 'v', # Ориентация графика ('v' - вертикальная, 'h' - горизонтальная)
             width = 1000, # ширина графика в пикселях
             height = 500 # высота графика в пикселях
            )
fig.show()

In [79]:
df_medals = px.data.medals_long()
display(df_medals.head(3))
fig = px.bar(data_frame = df_medals, 
             x = "nation", 
             y = "count", 
             color = "medal",
             title = "Long-Form Input",
             color_discrete_sequence = ['green', 'violet','blue'],
            )
fig.show()

        nation medal  count
0  South Korea  gold     24
1        China  gold     10
2       Canada  gold      9

In [16]:
df_medals = px.data.medals_long()
fig = px.bar(data_frame = df_medals, 
             x = "medal", 
             y = "count", 
             color = "nation",
             title = "Long-Form Input",
             pattern_shape = "nation",
             pattern_shape_sequence = [".", "x", "+"]
            )
fig.show()

In [17]:
# Матрица баров
df_tips = px.data.tips()
fig = px.bar(data_frame = df_tips,
             x = "sex",
             y = "total_bill",
             color = "smoker",
             barmode = "group",
             facet_row = "time",
             facet_col = "day",
             category_orders={"day": ["Thur", "Fri", "Sat", "Sun"],
                              "time": ["Lunch", "Dinner"]})
fig.show()

In [18]:
# Добавим анимацию
df_gapminder = px.data.gapminder().query("country in ['Germany', 'Spain', 'France']")
df_gapminder['popMillion'] = df_gapminder['pop']/1000000
fig = px.bar(
    data_frame = df_gapminder, 
    x = 'country',                # страна вместо года (чтобы бар был один и "рос" по годам)
    y = 'popMillion',
    title = 'Total Population of Germany by Year',
    color = 'lifeExp',
    text_auto = True,
    labels = {'year':'Год', 'popMillion':'Население (млн.)'},
    orientation = 'v',
    animation_frame = 'year',
    width = 1000, # ширина графика в пикселях
    height = 500 # высота графика в пикселях
)

fig.show()

### <font color='rebeccapurple'>5. Круговые диаграммы</font>

In [19]:
df_gapminder_2007 = px.data.gapminder().query("year == 2007")
df_gapminder_2007.head(20)

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32
71,Australia,Oceania,2007,81.235,20434176,34435.367440,AUS,36
83,Austria,Europe,2007,79.829,8199783,36126.492700,AUT,40
95,Bahrain,Asia,2007,75.635,708573,29796.048340,BHR,48
107,Bangladesh,Asia,2007,64.062,150448339,1391.253792,BGD,50
119,Belgium,Europe,2007,79.441,10392226,33692.605080,BEL,56
131,Benin,Africa,2007,56.728,8078314,1441.284873,BEN,204
143,Bolivia,Americas,2007,65.554,9119152,3822.137084,BOL,68
155,Bosnia and Herzegovina,Europe,2007,74.852,4552198,7446.298803,BIH,70
167,Botswana,Africa,2007,50.728,1639131,12569.851770,BWA,72
179,Brazil,Americas,2007,72.390,190010647,9065.800825,BRA,76
191,Bulgaria,Europe,2007,73.005,7322858,10680.792820,BGR,100
203,Burkina Faso,Africa,2007,52.295,14326203,1217.032994,BFA,854
215,Burundi,Africa,2007,49.580,8390505,430.070692,BDI,108
227,Cambodia,Asia,2007,59.723,14131858,1713.778686,KHM,116
239,Cameroon,Africa,2007,50.430,17696293,2042.095240,CMR,120

In [20]:
fig = px.pie(data_frame = df_gapminder_2007,
             names = 'continent', # Категории для "кусочков" диаграммы
             title = 'Country Distribution by Continent in 2007')
fig.show()

In [63]:
# Настройка отображения информации
fig = px.pie(data_frame = df_gapminder_2007,
             names = 'continent', # Категории для "кусочков" диаграммы
             title = 'Country Distribution by Continent in 2007',
             hover_data = ['country'], # Включает дополнительные данные (названия стран) при наведении курсора на срезы.
             # labels = {'country':'Country Name'}# Настраивает метки для наведенных данных.
            )
fig.update_traces( # обновить данные объектов
    textinfo = 'percent+label', # Как подписать данные на диаграмме
    pull = [0, 0.1, 0, 0, 0] # Выделение отдельного кусочка пирога
)
fig.show()

In [65]:
# Отверстие в центре
fig = px.pie(data_frame = df_gapminder_2007,
             names = 'continent', # Категории для "кусочков" диаграммы
             title = 'Country Distribution by Continent in 2007',
             hover_data = ['country'], # Включает дополнительные данные (названия стран) при наведении курсора на срезы.
             labels = {'country':'Country Name'}, # Настраивает метки для наведенных данных.
             hole = 0.5
            )
fig.update_traces( # обновить данные объекьлв
    textinfo = 'percent+label', # Как подписать данные на диаграмме
    pull = [0, 0.1, 0, 0, 0] # Выделение отдельного кусочка пирога
)
fig.show()

Ссылка на документацию по объекту figure библиотеки Plotly [Figure_Plotly](https://plotly.com/python-api-reference/generated/plotly.graph_objects.Figure.html)

### <font color='rebeccapurple'>6. Scatter plot</font>

In [23]:
df_iris = px.data.iris()
df_iris.head(3)

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1

In [24]:
fig = px.scatter(
    data_frame = df_iris, 
    x = 'sepal_length', 
    y = 'sepal_width', 
    color = 'species', 
    title = 'Iris Dataset: Sepal Width vs Sepal Length')
fig.show()

##### <font color='rebeccapurple'>6.1. Пузырьковая диаграмма</font>

In [25]:
fig = px.scatter(
    data_frame = df_iris, 
    x = 'sepal_length', 
    y = 'sepal_width', 
    color = 'species',
    size = 'petal_length', # Размер точки будет зависеть от длины лепестка
    title = 'Iris Dataset: Sepal Width vs Sepal Length')
fig.show()

In [26]:
! pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.6-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels) (2.4.4)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels) (1.17.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels) (2.3.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels) (26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Vitaliy\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.6-cp313-cp313-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.5 MB 12.6 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 36.5 MB/s  0:00:00
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Installing collected packages: patsy, statsmodels

   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   ---------------------------------------- 2/2 [statsmodels]

Successfully installed patsy-1.0.2 statsmodels-0.14.6

In [27]:
# Добавление линии тренда
fig = px.scatter(
    data_frame = df_iris, 
    x = 'sepal_length', 
    y = 'sepal_width', 
    color = 'species',
    size = 'petal_length', # Размер точки будет зависеть от длины лепестка
    trendline = 'lowess', # lowess
    title = 'Iris Dataset: Sepal Width vs Sepal Length')
fig.show()

In [66]:
# Другие параметры
fig = px.scatter(
    data_frame = df_iris, 
    x = 'sepal_length', 
    y = 'sepal_width', 
    color = 'species',
    size = 'petal_length', # Размер точки будет зависеть от длины лепестка
    # symbol = 'species', # Отображение каждого вида разной фигурой
    # text = 'sepal_length', # Какой текст отображать на точках
    labels = ({'sepal_length':'Длина лепестка', 'sepal_width':'Ширина лепестка'}),
    color_discrete_sequence = ['green', 'yellow', 'black'], # зменение цвета для каждой группы
    size_max = 10, # максимальный размер точки при использовании параметра size
    marginal_x = "histogram", 
    marginal_y = "histogram",
    title = 'Iris Dataset: Sepal Width vs Sepal Length')
fig.show()

### <font color='rebeccapurple'>7. Box plot</font>

In [29]:
df_tips = px.data.tips()
df_tips.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [67]:
fig = px.box(data_frame = df_tips,
             y = 'total_bill',
             animation_frame= 'day',
             title = 'Distribution of Total Bills')
fig.show()

In [31]:
# сделаем разбивку по дням недели
fig = px.box(data_frame = df_tips,
             x = 'day',
             y = 'total_bill',
             title = 'Distribution of Total Bills')
fig.show()

In [32]:
# Добавим для каждого дня недели цветовую разбивку
fig = px.box(data_frame = df_tips,
             x = 'day',
             y = 'total_bill',
             color = 'smoker',
             title = 'Distribution of Total Bills')
fig.show()

In [33]:
# Добавим визуализацию доверительного интервала
# Доверительный интервал - это отрезок значений, в котором с вероятностью 95% находится значение
fig = px.box(data_frame = df_tips,
             x = 'day',
             y = 'total_bill',
             color = 'smoker',
             notched = True, # включение отображения Д
             points = 'all', # отображение всех точек
             title = 'Distribution of Total Bills')
fig.show()

In [34]:
# Другие параметры
fig = px.box(data_frame = df_tips,
             x = 'day',
             y = 'total_bill',
             color = 'smoker',
             notched = True, # включение отображения Д
             # points = 'all', # отображение всех точек
             labels = ({'day':'день недели', 'total_bill':'сумма чека'}),
             boxmode = 'overlay', # Расположение боксплотов относительно друг друга: 'group','overlay'
             title = 'Distribution of Total Bills')
fig.show()

In [35]:
# Матрица боксплотов
fig = px.box(data_frame = df_tips,
             x = 'day',
             y = 'total_bill',
             labels = ({'day':'день недели', 'total_bill':'сумма чека'}),
             facet_row = 'smoker',
             facet_col = 'sex',
             title = 'Distribution of Total Bills')
fig.show()

### <font color='rebeccapurple'>8. Heatmap</font>

In [36]:
import seaborn as sns
df_flights = sns.load_dataset("flights")
df_flights.head(3)

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132

In [37]:
df_flights_pivot = df_flights.pivot_table(index = 'month',
                                         columns = 'year',
                                         values = 'passengers')
df_flights_pivot

C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_21880\2458703914.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df_flights_pivot = df_flights.pivot_table(index = 'month',

year,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960
month,,,,,,,,,,,,
Jan,112.0,115.0,145.0,171.0,196.0,204.0,242.0,284.0,315.0,340.0,360.0,417.0
Feb,118.0,126.0,150.0,180.0,196.0,188.0,233.0,277.0,301.0,318.0,342.0,391.0
Mar,132.0,141.0,178.0,193.0,236.0,235.0,267.0,317.0,356.0,362.0,406.0,419.0
Apr,129.0,135.0,163.0,181.0,235.0,227.0,269.0,313.0,348.0,348.0,396.0,461.0
May,121.0,125.0,172.0,183.0,229.0,234.0,270.0,318.0,355.0,363.0,420.0,472.0
Jun,135.0,149.0,178.0,218.0,243.0,264.0,315.0,374.0,422.0,435.0,472.0,535.0
Jul,148.0,170.0,199.0,230.0,264.0,302.0,364.0,413.0,465.0,491.0,548.0,622.0
Aug,148.0,170.0,199.0,242.0,272.0,293.0,347.0,405.0,467.0,505.0,559.0,606.0
Sep,136.0,158.0,184.0,209.0,237.0,259.0,312.0,355.0,404.0,404.0,463.0,508.0
Oct,119.0,133.0,162.0,191.0,211.0,229.0,274.0,306.0,347.0,359.0,407.0,461.0
Nov,104.0,114.0,146.0,172.0,180.0,203.0,237.0,271.0,305.0,310.0,362.0,390.0
Dec,118.0,140.0,166.0,194.0,201.0,229.0,278.0,306.0,336.0,337.0,405.0,432.0

In [38]:
fig = px.imshow(df_flights_pivot,
                labels = ({'x':'Year', 'y':'Month','color':'Passengers'}),
                title = 'Monthly Passenger Numbers Over Years')
fig.show()

In [70]:
# Настроим цветовую шкалу и добавим текст
fig = px.imshow(df_flights_pivot,
                labels = ({'x':'Year', 'y':'Month','color':'Passengers'}),
                aspect = 'auto', # Настройка соотношений сторон ('auto', 'equal', None)
                color_continuous_scale = 'Viridis', # Градиентная раскраска
                text_auto = True, # Отображение значений
                title = 'Monthly Passenger Numbers Over Years')
fig.show()

### <font color='rebeccapurple'>9. Sunburst charts</font>
Лучевые диаграммы эффективны для визуализации иерархических структур данных и пропорций внутри них, показывая, как одно кольцо, уровень в иерархии, разбивается на составляющие его части.

In [40]:
fig = px.sunburst(data_frame = df_tips,
                  path = ['smoker','day', 'time', 'sex'], # Уровни иерархии для диаграммы
                  values = 'total_bill', # На основе этого поля определяется размер каждого сегмента
                  color = 'time', # Поле, на основе которого раскрашивается секторы
                  title = 'Distribution of Total Bills by Day, Time, and Sex')
fig.show()

In [41]:
# зменим цветовую шкалу и настроим текст внутри графика
fig = px.sunburst(data_frame = df_tips,
                  path = ['day', 'time', 'sex'], # Уровни иерархии для диаграммы
                  values = 'total_bill', # На основе этого поля определяется размер каждого сегмента
                  color = 'total_bill', # Поле, на основе которого раскрашивается секторы
                  color_continuous_scale = 'Blues',
                  title = 'Distribution of Total Bills by Day, Time, and Sex')
fig.update_traces(textinfo = 'label+percent entry')
fig.show()

### <font color='rebeccapurple'>10. Настройка графиков в Plotly</font>
<b> update_layout </b> - настраивает оформление графика (рамку, оси, легенду, фон). <br>
<b> update_traces </b> - настраивает сами данные (точки, линии, бары и т.п.).

In [42]:
import plotly.express as px

df_iris = px.data.iris()
fig = px.scatter(data_frame = df_iris,
                 x = 'sepal_length',
                 y = 'sepal_width',
                 color = 'species',
                 title = 'Iris Dataset: Sepal Width vs Sepal Length'
                )
fig.show()

##### <font color='rebeccapurple'>10.1. Управление заголовком и названиями осей</font>

In [43]:
fig.update_layout(
    title = 'Iris Flower Measurements',
    xaxis_title = 'Sepal Length (cm)',
    yaxis_title = 'Sepal Width (cm)'
)
fig.show()

##### <font color='rebeccapurple'>10.2. Управление легендой</font>
<i> Расположение легенды: </i>
- x = 0 - левая граница области графика
- x = 1 - правая граница
- y = 0 - низ
- y = 1 - верх

In [75]:
fig.update_layout(
    legend_title = 'Species',
    legend = {'x':1,
              'y':1,
              'bordercolor':'black',
              'borderwidth': 1}
)
fig.show()

##### <font color='rebeccapurple'>10.3. Аннотации</font>

In [76]:
fig.add_annotation(
    x = 5, # Координаты, на которые должна быть направлена аннотация.
    y = 3.5,
    text = "Outlier", # Текст аннотации
    showarrow = True, # Показывать ли стрелку, указывающую на аннотируемую точку.
    arrowhead = 1, # Стиль наконечника стрелки
    ax = 20, # Положение хвоста стрелки (сдвиг по оси x)
    ay = -30  # Положение хвоста стрелки (сдвиг по оси y)
)
fig.show()

##### <font color='rebeccapurple'>10.4. Внешний вид графика</font>

In [46]:
fig.update_layout(
    plot_bgcolor = 'lightgrey',  # Цвет фона области построения
    paper_bgcolor = 'white',     # Цвет фона за пределами области построения
    font = {'family':'Courier New, monospace',
            'size':12,
            'color':"RebeccaPurple"}
)
fig.show()

In [78]:
from plotly.subplots import make_subplots
df_Germany = px.data.gapminder().query("country=='Germany'") 
df_Germany['popMillion'] = df_Germany['pop']

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(
px.bar(data_frame = df_Germany,x = 'year', y = 'popMillion', color_discrete_sequence = ['green']).data[0],
secondary_y=False
)

fig.add_trace(
px.bar(data_frame = df_Germany,x = 'year', y = 'lifeExp', color_discrete_sequence = ['red']).data[0],
secondary_y=True
)
fig.show()