In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
df = pd.read_csv('../data/spotify_songs.csv')
df

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-2.634,1,0.0583,0.102000,0.000000,0.0653,0.5180,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,11,-4.969,1,0.0373,0.072400,0.004210,0.3570,0.6930,99.972,162600
2,1z1Hg7Vb0AhHDiEmnDE79l,All the Time - Don Diablo Remix,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-3.432,0,0.0742,0.079400,0.000023,0.1100,0.6130,124.008,176616
3,75FpbthrwQmzHlBJLuGdC7,Call You Mine - Keanu Silva Remix,The Chainsmokers,60,1nqYsOef1yKKuGOVchbsk6,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,7,-3.778,1,0.1020,0.028700,0.000009,0.2040,0.2770,121.956,169093
4,1e8PAfcKUYoKkxPhrHqw4x,Someone You Loved - Future Humans Remix,Lewis Capaldi,69,7m7vv9wlQ4i0LFuJiE2zsQ,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-4.672,1,0.0359,0.080300,0.000000,0.0833,0.7250,123.976,189052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32828,7bxnKAamR3snQ1VGLuVfC1,City Of Lights - Official Radio Edit,Lush & Simon,42,2azRoBBWEEEYhqV6sb7JrT,City Of Lights (Vocal Mix),2014-04-28,в™Ґ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,2,-1.814,1,0.0936,0.076600,0.000000,0.0668,0.2100,128.170,204375
32829,5Aevni09Em4575077nkWHz,Closer - Sultan & Ned Shepard Remix,Tegan and Sara,20,6kD6KLxj7s8eCE3ABvAyf5,Closer Remixed,2013-03-08,в™Ґ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,0,-4.462,1,0.0420,0.001710,0.004270,0.3750,0.4000,128.041,353120
32830,7ImMqPP3Q1yfUHvsdn7wEo,Sweet Surrender - Radio Edit,Starkillers,14,0ltWNSY9JgxoIZO4VzuCa6,Sweet Surrender (Radio Edit),2014-04-21,в™Ґ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,6,-4.899,0,0.0481,0.108000,0.000001,0.1500,0.4360,127.989,210112
32831,2m69mhnfQ1Oq6lGtXuYhgX,Only For You - Maor Levi Remix,Mat Zo,15,1fGrOkHnHJcStl14zNx8Jy,Only For You (Remixes),2014-01-01,в™Ґ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,2,-3.361,1,0.1090,0.007920,0.127000,0.3430,0.3080,128.008,367432
32832,29zWqhca3zt5NsckZqDf6c,Typhoon - Original Mix,Julian Calor,27,0X3mUOm6MhxR7PzxG95rAo,Typhoon/Storm,2014-03-03,в™Ґ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,5,-4.571,0,0.0385,0.000133,0.341000,0.7420,0.0894,127.984,337500

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32833 entries, 0 to 32832
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_id                  32833 non-null  object
 1   track_name                32828 non-null  object
 2   track_artist              32828 non-null  object
 3   track_popularity          32833 non-null  int64
 4   track_album_id            32833 non-null  object
 5   track_album_name          32828 non-null  object
 6   track_album_release_date  32833 non-null  object
 7   playlist_name             32833 non-null  object
 8   playlist_id               32833 non-null  object
 9   playlist_genre            32833 non-null  object
 10  playlist_subgenre         32833 non-null  object
 11  danceability              32833 non-null  float64
 12  energy                    32833 non-null  float64
 13  key                       32833 non-null  int64
 14  loudness                  32833 non-null  float64
 15  mode                      32833 non-null  int64
 16  speechiness               32833 non-null  float64
 17  acousticness              32833 non-null  float64
 18  instrumentalness          32833 non-null  float64
 19  liveness                  32833 non-null  float64
 20  valence                   32833 non-null  float64
 21  tempo                     32833 non-null  float64
 22  duration_ms               32833 non-null  int64
dtypes: float64(9), int64(4), object(10)
memory usage: 5.8+ MB

In [ ]:
df_track = df[df['track_popularity'] > 90]
df_track

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
139,6cy3ki60hLwimwIje7tALf,RITMO (Bad Boys For Life),The Black Eyed Peas,96,6EobpC5SDFy5DF50dWNVGF,RITMO (Bad Boys For Life),2019-10-12,Dance Pop,37i9dQZF1DWZQaaqNMbbXa,pop,...,10,-7.037,0,0.0657,0.0334,0.000840,0.2370,0.6670,104.994,221714
179,7CHi4DtfK4heMlQaudCuHK,Lose Control,MEDUZA,91,1qSOaTvsCOyFJya3v1UzkP,Lose Control,2019-10-11,Dance Room,37i9dQZF1DX2ENAPP1Tyed,pop,...,10,-8.659,0,0.0415,0.1290,0.000000,0.1400,0.5290,123.935,168387
344,2Fxmhks0bxGSBdJ92vM42m,bad guy,Billie Eilish,95,0S0KGZnfBGSIssfF54WSJh,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",2019-03-29,Pop Warmup 130 BPM,37i9dQZF1DX3PIAZMcbo2T,pop,...,7,-10.965,1,0.3750,0.3280,0.130000,0.1000,0.5620,135.128,194088
646,2tnVG71enUj33Ic2nFN6kZ,Ride It,Regard,94,4zOhjJfe0dwqsNdDYk622E,Ride It,2019-07-26,Pop / Dance,6mXh8CUBMBsBUu88a4eAQV,pop,...,7,-4.258,0,0.0874,0.1770,0.000064,0.1060,0.8840,117.948,157606
687,7k4t7uLgtOxPwTpFmtJNTY,Tusa,KAROL G,98,7mKevNHhVnZER3BLgI8O4F,Tusa,2019-11-07,Todo Г‰xitos,2ji5tRQVfnhaX1w9FhmSzk,pop,...,2,-3.280,1,0.2980,0.2950,0.000134,0.0574,0.5740,101.085,200960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30270,4vUmTMuQqjdnvlZmAH61Qk,South of the Border (feat. Camila Cabello & Ca...,Ed Sheeran,91,3oIFxDIo2fwuk4lwCmFZCx,No.6 Collaborations Project,2019-07-12,Charts 2020 рџ”ҐTop 2020рџ”ҐHits 2020рџ”ҐSummer 2020рџ”ҐPo...,3xMQTDLOIGvj3lWH5e5x6F,edm,...,9,-6.376,0,0.0824,0.1480,0.000000,0.0865,0.6680,97.986,204467
30337,51Fjme0JiitpyXKuyQiCDo,Lalala,Y2K,91,4WlC4FXhonJhNTXCQPGP3r,Lalala,2019-06-28,VerГЈo 2020 | Pop | Funk | Sertanejo | EDM | To...,5HmZtuuIDMtIy21kylqhx6,edm,...,2,-7.899,1,0.0845,0.1810,0.000000,0.1370,0.4960,129.972,160627
30387,2wrJq5XKLnmhRXHIAf9xBa,"10,000 Hours (with Justin Bieber)",Dan + Shay,91,4ow6xJwn49gpWz7iHpOzWY,"10,000 Hours (with Justin Bieber)",2019-10-04,2010 - 2011 - 2012 - 2013 - 2014 - 2015 - 2016...,2DjIfVDXGYDgRxw7IJTKVb,edm,...,10,-4.644,1,0.0259,0.1530,0.000000,0.1110,0.4300,89.991,167693
30388,1HfMVBKM75vxSfsQ5VefZ5,Lose You To Love Me,Selena Gomez,93,3tBkjgxDqAwss76O1YHsSY,Lose You To Love Me,2019-10-23,2010 - 2011 - 2012 - 2013 - 2014 - 2015 - 2016...,2DjIfVDXGYDgRxw7IJTKVb,edm,...,4,-9.005,1,0.0438,0.5760,0.000000,0.2100,0.0916,101.993,206459
30423,0TK2YIli7K1leLovkQiNik,SeГ±orita,Shawn Mendes,93,2ZaX1FdZCwchXl1QZiD4O4,SeГ±orita,2019-06-21,2010 - 2011 - 2012 - 2013 - 2014 - 2015 - 2016...,2DjIfVDXGYDgRxw7IJTKVb,edm,...,9,-6.039,0,0.0287,0.0370,0.000000,0.0945,0.7500,116.947,190960

In [7]:
from dash import Dash, html, dcc, callback, Output, Input
import plotly.express as px

df = pd.read_csv('../data/spotify_songs.csv')

df_track = df[df['track_popularity'] > 80]

df_genres = df['playlist_genre'].unique().tolist()


app = Dash()

app.layout = [
html.Div(html.H2('My First App with Graph and Controls')),
dcc.RadioItems(options=df_genres, 
               value=df_genres[0], id='controls-and-radio-item'),
dcc.Graph(figure={}, id='controls-and-graph')
]
@callback(
Output(component_id='controls-and-graph', component_property='figure'),
Input(component_id='controls-and-radio-item', component_property='value')
)
def update_graph(col_chosen):
    fig = px.scatter(df_track[df_track['playlist_genre'] == col_chosen]
                 , x = 'track_popularity'
                 , y = 'duration_ms'
           
) 
    return fig

app.run(port= 8052)