# <b><font color='rebeccapurple'>Продвинутые возможности Plotly</font></b>
[Prompt](https://mipt-stats.gitlab.io/courses/ad_fivt/plotly.html)

### <font color='rebeccapurple'>1. 3D графики</font>

##### <font color='rebeccapurple'>1.1. 3D диаграмма рассеяния</font>

In [2]:
# мпорт библиотек
import plotly.express as px

In [3]:
# Загрузка данных
df_iris = px.data.iris()
df_iris.head(3)

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1

In [4]:
# Построение графика
fig = px.scatter_3d(
    data_frame = df_iris, # Датафрейм, на основе которого строится график
    x = 'sepal_length', # Значения для оси X
    y = 'sepal_width', # Значения для оси Y
    z = 'petal_width', # Значения для оси Z
    color = 'species', # Поле для разделения точек по цвету
    size = 'sepal_length',
    size_max = 10) 
fig.show()

##### <font color='rebeccapurple'>1.2. 3D график поверхности</font>
Чтобы создать график поверхности, нам нужна структурированная сетка точек (x, y) и соответствующие значения z, которые определяют высоту поверхности в каждой точке.

In [5]:
import plotly.graph_objects as go
import numpy as np

x = np.linspace(-5, 5, 50) # координаты X
y = np.linspace(-5, 5, 50) # координаты Y
x, y = np.meshgrid(x, y) # структурированная сетка точек
z = np.sin(np.sqrt(x ** 2 + y ** 2)) # значения z, которые определяют высоту поверхности в каждой точке.

fig = go.Figure(
    data = [go.Surface(
        z = z,
        x = x,
        y = y)
           ]
)
fig.update_layout(title = '3D Surface Plot',# заголовок графика
                  width = 500, # ширина графика в пикселях
                  height = 500, # высота графика в пикселях
                 )
fig.show()

### <font color='rebeccapurple'>2. Graphic Objects</font>
Graph Objects - это строительные блоки графиков Plotly. Каждый элемент графика (например, линии, маркеры, текст) представлен в виде объекта с собственным набором настраиваемых атрибутов.

In [6]:
import plotly.graph_objects as go
fig = go.Figure() # инициализация нового объекта фигуры
# Добавление новой трассировки к фигуре. 
# go.Scatter используется для создания линейного графика (диаграммы рассеяния в линейном режиме).
fig.add_trace(
    go.Scatter(
        x = [1, 2, 3, 4],
        y = [10, 11, 12, 13],
        mode = 'lines'
    )
)
# Обновление настройки макета фигуры, такие как заголовки и метки осей.
fig.update_layout(
    title = 'Simple Line Chart',
    xaxis_title = 'X Axis',
    yaxis_title = 'Y Axis')
fig.show()

In [7]:
fig.update_traces(line = {'color' : 'RoyalBlue', 'width' : 4})#  зменение свойств трассировок, такие как цвет и ширина линии
# Добавление аннотации к графику. Параметры x, y и text задают положение и содержание аннотации.
fig.add_annotation(x = 3, y = 12, text = "Highlight", showarrow = True, arrowhead = 1)
# Дальнейшая настройка макета, например цвет фона графика.
fig.update_layout(plot_bgcolor = 'lightgrey')
fig.show()

### <font color='rebeccapurple'>3. Подграфики и множественные оси в Plotly</font>

In [8]:
# Создание фигуры с несколькими подграфиками
from plotly.subplots import make_subplots

fig = make_subplots(rows = 2, cols = 1)

fig.add_trace(go.Scatter(x = [1, 2, 3], y = [4, 5, 6], name = 'Line 1'), row = 1, col = 1)
fig.add_trace(go.Scatter(x = [1, 2, 3], y = [6, 7, 8], name = 'Line 2'), row = 2, col = 1)

fig.show()

In [9]:
# Общие оси Y
fig = make_subplots(rows = 1, cols = 4, #shared_yaxes = True
                    )

fig.add_trace(go.Scatter(x = [1, 2, 3], y = [2, 3, 4]), row = 1, col = 1)
fig.add_trace(go.Scatter(x = [20, 30, 40], y = [5, 5, 5]), row = 1, col = 2)
fig.add_trace(go.Scatter(x = [2, 3, 4], y = [600, 700, 800]), row = 1, col = 3)
fig.add_trace(go.Scatter(x = [4000, 5000, 6000], y = [7000, 8000, 9000]), row = 1, col = 4)

fig.update_layout(height = 600, width = 1000, title_text = "Multiple Subplots with Shared Y-Axes")
fig.show()

In [10]:
# Две оси Y
fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Scatter(x = [1, 2, 3], y = [2, 3, 4]), secondary_y = False)
fig.add_trace(go.Scatter(x = [1, 2, 3], y = [5, 5, 5]), secondary_y = True)

fig.update_layout(height = 600, width = 1000, title_text = "Multiple Subplots with Shared Y-Axes")
fig.show()

In [11]:
# Настройка макетов подграфиков
fig = make_subplots(
    rows = 2, cols = 2, 
    vertical_spacing = 0.1, # Расстояние между подграфиками (от 0 до 1)
    subplot_titles=("Plot 1", "Plot 2", "Plot 3", "Plot 4") # Названия графиков
)

fig.add_trace(go.Scatter(x = [1, 2, 3], y = [2, 3, 4]), row = 1, col = 1)
fig.add_trace(go.Scatter(x = [20, 30, 40], y=[5, 5, 5]), row = 1, col = 2)
fig.add_trace(go.Scatter(x = [2, 3, 4], y = [600, 700, 800]), row = 2, col = 1)
fig.add_trace(go.Scatter(x = [4000, 5000, 6000], y = [7000, 8000, 9000]), row = 2, col = 2)

fig.update_layout(height = 600, width = 1000, title_text = "Customized Subplots Layout")
fig.show()

### <font color='rebeccapurple'>4. Взаимодействие с графиками в Plotly</font>

##### <font color='rebeccapurple'>4.1. Масштабирование и панорамирование</font>

In [12]:
fig = go.Figure(data = go.Scatter(x = [1, 2, 3], y = [4, 5, 6]))
fig.update_layout(
    title = 'Zoom and Pan Example',
    # Ползунок диапазона к оси x, позволяющий пользователям выбирать диапазон для увеличения.
    xaxis = {'rangeslider' : {'visible' : True}},
    # Установка этого значения в False позволяет панорамировать вдоль оси y.
    yaxis = {'fixedrange' : False}
)
fig.show()

##### <font color='rebeccapurple'>4.2. Всплывающие подсказки</font>

In [13]:
fig = go.Figure(data = go.Scatter(x = [1, 2, 3], y = [4, 5, 6],
                                  mode = 'markers',
                                  # Указывает информацию, которая должна отображаться при наведении курсора на точки. 
                                  # Она может включать координаты данных (x, y), текст и многое другое.
                                  hoverinfo = 'x+y+text',
                                  # Пользовательский текст, который может отображаться во всплывающих подсказках.
                                  text = ['Point 1', 'Point 2', 'Point 3']))
fig.show()

##### <font color='rebeccapurple'>4.3. Добавление кнопок и выпадающих меню</font>

In [14]:
fig = go.Figure(data = [go.Scatter(x = [1, 2, 3], y = [4, 5, 6], mode = 'markers')])

fig.update_layout(
    # Настраивает выпадающие меню или кнопки на графике
    updatemenus = [
        {
            # Определяет отдельные кнопки в выпадающем меню, 
            # указывая команду (args), метку 
            # и метод (restyle для обновления атрибутов данных, relayout для атрибутов макета).
            'buttons' : [
                {'args' : ['type', 'scatter'], 
                 'label' : 'Scatter Plot', 
                 'method' : 'restyle'},
                {'args' : ['type', 'bar'], 
                 'label' : 'Bar Chart', 
                 'method' : 'restyle'},
                {'args' : ['type', 'histogram'], 
                 'label' : 'Histogram', 
                 'method' : 'restyle'}
            ],
            'direction' : 'down',
            'showactive' : True
        }
    ]    
)
fig.show()

##### <font color='rebeccapurple'>4.4. Параметры конфигурации</font>

In [15]:
fig.show(config = {
    'displayModeBar': True, # Всегда показывать панель режимов
    'scrollZoom': True # Включить масштабирование прокрутки
})

### <font color='rebeccapurple'>5. Задача - анализ транзакций покупок кофе</font>

##### <font color='rebeccapurple'>Описание данных</font>
- hour_of_day - час дня
- cash_type - тип оплаты (card)
- money - сумма оплаты
- coffee_name - вид кофе
- Time_of_Day - время суток
- Weekday - день недели
- Month_name - месяц
- Weekdaysort - номер дня недели
- Monthsort - номер месяца
- Date - дата
- Time - время

In [23]:
# Загрузите данные в DataFrame df_coffee
import pandas as pd
import plotly.express as px

df_coffee = pd.read_csv('../data/Coffe_sales.csv')
df_coffee

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.70,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000
1,12,card,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000
2,12,card,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000
3,13,card,28.90,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33.006000
4,13,card,38.70,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000
...,...,...,...,...,...,...,...,...,...,...,...
3542,10,card,35.76,Cappuccino,Morning,Sun,Mar,7,3,2025-03-23,10:34:54.894000
3543,14,card,35.76,Cocoa,Afternoon,Sun,Mar,7,3,2025-03-23,14:43:37.362000
3544,14,card,35.76,Cocoa,Afternoon,Sun,Mar,7,3,2025-03-23,14:44:16.864000
3545,15,card,25.96,Americano,Afternoon,Sun,Mar,7,3,2025-03-23,15:47:28.723000
3546,18,card,35.76,Latte,Night,Sun,Mar,7,3,2025-03-23,18:11:38.635000

In [17]:
# В df_coffee создайте новый столбец DateTime, объединив столбцы Date и Time
# Тип данных нового столбца - datetime
df_coffee['Date+time'] = pd.to_datetime(df_coffee['Date'] +' '+ df_coffee['Time'])
df_coffee

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time,Date+time
0,10,card,38.70,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000,2024-03-01 10:15:50.520
1,12,card,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000,2024-03-01 12:19:22.539
2,12,card,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000,2024-03-01 12:20:18.089
3,13,card,28.90,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33.006000,2024-03-01 13:46:33.006
4,13,card,38.70,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000,2024-03-01 13:48:14.626
...,...,...,...,...,...,...,...,...,...,...,...,...
3542,10,card,35.76,Cappuccino,Morning,Sun,Mar,7,3,2025-03-23,10:34:54.894000,2025-03-23 10:34:54.894
3543,14,card,35.76,Cocoa,Afternoon,Sun,Mar,7,3,2025-03-23,14:43:37.362000,2025-03-23 14:43:37.362
3544,14,card,35.76,Cocoa,Afternoon,Sun,Mar,7,3,2025-03-23,14:44:16.864000,2025-03-23 14:44:16.864
3545,15,card,25.96,Americano,Afternoon,Sun,Mar,7,3,2025-03-23,15:47:28.723000,2025-03-23 15:47:28.723
3546,18,card,35.76,Latte,Night,Sun,Mar,7,3,2025-03-23,18:11:38.635000,2025-03-23 18:11:38.635

In [18]:
# Для датафрейма df_coffee нарисуйте 3D диаграмму рассеяния с параметрами:
# по оси X - месяц
# по оси Y - время суток
# по оси Z - день недели
# цвет точек зависит от вида кофе
fig = px.scatter_3d(df_coffee, 
                    x = 'Month_name', 
                    y = 'Time_of_Day', 
                    z = 'Weekday', 
                    color = 'coffee_name'
                    
                    )
fig.show()

In [30]:
fig = px.histogram(
    df_coffee,
    y='Weekday',
    color='coffee_name',
    category_orders={'Weekday': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']}
)
fig.update_layout(
    title='Coffee Sales by Weekday and Coffee Type',
    xaxis_title='Number of Sales',
    yaxis_title='Weekday',
    legend_title='Type of Coffee',

)
fig.show()

In [45]:
fig = px.histogram(
    df_coffee,
    y='Time_of_Day',
    color='coffee_name',
    category_orders={'Time_of_Day': ['Morning', 'Afternoon', 'Night']})
fig.show()

In [21]:
# Постройте круговую диаграмму, где сектора будут отображать виды кофе

In [22]:
# Настройте график с выпадающим меню: Scatter Plot и Bar Chart
# График должен отображать количество покупок кофе в каждый час дня