## <b><font color='lightcoral'>Продвинутые возможности группировки и  работы с jupyter notebook</font></b>

In [2]:
import pandas as pd
appointments = pd.read_excel('../data/appointments.xlsx', 'Sheet1')
appointments

,Время приема,Врач,Специальность,Пациент,Поставленный диагноз,Назначение
0,2025-09-03 21:52,Сидорова А.А.,невролог,Тимофеев Панкратий Феофанович,Сахарный диабет,Обезболивающие
1,2025-09-07 03:41,Смирнов С.С.,офтальмолог,Лихачев Модест Герасимович,Бронхит,Постельный режим
2,2025-08-12 20:19,Сидорова А.А.,невролог,Субботин Август Васильевич,Гипертония,Обследование
3,2025-09-04 13:38,Федоров Ф.Ф.,уролог,Людмила Робертовна Логинова,ОРВ,Снижение физических нагрузок
4,2025-09-07 13:28,ванов ..,терапевт,Милица Александровна Дьячкова,ОРВ,Антибиотики
...,...,...,...,...,...,...
95,2025-09-01 06:29,Смирнов С.С.,офтальмолог,Митофан Тихонович Сергеев,Бронхит,Физиотерапия
96,2025-08-19 13:22,Сидорова А.А.,невролог,Мельникова Агафья Сергеевна,Сахарный диабет,Гимнастика
97,2025-09-04 05:49,Морозов М.М.,хирург,Харлампий Дорофеевич Белозеров,Аллергический ринит,Постельный режим
98,2025-09-09 06:07,Петров П.П.,кардиолог,Емельянова Лора Антоновна,Конъюнктивит,Физиотерапия
99,2025-08-12 08:46,Егорова Е.Е.,дерматолог,Натан Фадеевич Самсонов,ОРВ,Гимнастика

<i> Задача: </i><br>
Посчитать, сколько раз за предыдущий месяц каждый врач ставил какой-либо диагноз. <br>
Результаты представить в виде таблицы, в которой посчитать суммы по строкам и столбцам, т.е. сколько врач сделал приемов за месяц и сколько раз конкретный диагноз поставлен всеми врачами.

### <font color='lightcoral'>1. Таблицы сопряженности (crosstab)</font>
<b>Синтаксис:</b>
-------------------------------
##### pd.crosstab(index, columns, values=None, rownames=None, colnames=None, aggfunc=None, margins=False, margins_name='All', dropna=True)
-------------------------------
- <i>index</i> — значения для группировки по строкам;
- <i>columns</i> — значения для группировки по столбцам;
- <i>values</i> — агрегируемый столбец (или столбцы), его значения непосредственно определяют значения таблицы сопряженности;
- <i>aggfunc</i> — функция, которая будет применена к каждой группе значений values, сгруппированным по значениям index и columns. Значения этой функции и есть значения сводной таблицы;
- <i>rownames и colnames</i> — имена строк и столбцов таблицы сопряженности;
- <i>margins</i> — добавляет результирующий столбец/строку;
- <i>margins_name</i> — имя результирующего столбец/строку;
- <i>dropna</i> — не включать столбцы, которые состоят только из NaN;

In [3]:
pd.crosstab(appointments['Врач'], appointments['Поставленный диагноз'], margins = True, margins_name = 'тог')

Поставленный диагноз,Аллергический ринит,Ангина,Бронхит,Гастрит,Гипертония,Конъюнктивит,Мигрень,ОРВ,Остеохондроз,Сахарный диабет,тог
Врач,,,,,,,,,,,
Васильева В.В.,2,2,1,2,1,0,0,2,1,0,11
Егорова Е.Е.,1,1,0,4,0,0,0,2,3,3,14
ванов ..,1,0,0,1,1,0,0,1,0,1,5
Кузнецов К.К.,0,0,0,3,1,0,5,2,0,1,12
Морозов М.М.,1,2,0,3,2,1,2,0,0,0,11
Николаева Н.Н.,1,1,1,3,0,1,2,2,0,3,14
Петров П.П.,1,2,1,1,0,3,0,0,0,0,8
Сидорова А.А.,0,1,0,0,1,1,0,1,0,2,6
Смирнов С.С.,3,0,2,0,1,2,3,0,1,1,13
Федоров Ф.Ф.,0,0,0,0,1,1,0,2,0,2,6
тог,10,9,5,17,8,9,12,12,5,13,100

### <font color='lightcoral'>2. Сводные таблицы (pivot-table)</font>
<b>Синтаксис:</b>
-------------------------------
##### pd.pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')
-------------------------------
- <i>data</i> — исходная таблица;
- <i>values</i> — агрегируемый столбец, его значения непосредственно определяют значения сводной таблицы;
- <i>index</i> — ключи для группировки, относятся к индексам сводной таблицы;
- <i>columns</i> — ключи для группировки, относятся к столбцам сводной таблицы;
- <i>aggfunc</i> — функция, которая будет применена к каждой группе значений values, сгруппированным по значениям index и columns. Значения этой функции и есть значения сводной таблицы. Если передается список функций, то сводная таблица имеет иерархические имена колонок, верхние значения которых — имена функций;
- <i>fill_value</i> — значения для замены пропусков;
- <i>dropna</i> — не включать столбцы, которые состоят только из NaN;
- <i>margins</i> — добавляет результирующий столбец/строку;
- <i>margins_name</i> — имя результирующего столбец/строку.

In [4]:
pd.pivot_table(appointments, index='Врач', columns='Поставленный диагноз', 
               aggfunc = "count", values = 'Время приема', fill_value = 0, margins=True)

Поставленный диагноз,Аллергический ринит,Ангина,Бронхит,Гастрит,Гипертония,Конъюнктивит,Мигрень,ОРВ,Остеохондроз,Сахарный диабет,All
Врач,,,,,,,,,,,
Васильева В.В.,2,2,1,2,1,0,0,2,1,0,11
Егорова Е.Е.,1,1,0,4,0,0,0,2,3,3,14
ванов ..,1,0,0,1,1,0,0,1,0,1,5
Кузнецов К.К.,0,0,0,3,1,0,5,2,0,1,12
Морозов М.М.,1,2,0,3,2,1,2,0,0,0,11
Николаева Н.Н.,1,1,1,3,0,1,2,2,0,3,14
Петров П.П.,1,2,1,1,0,3,0,0,0,0,8
Сидорова А.А.,0,1,0,0,1,1,0,1,0,2,6
Смирнов С.С.,3,0,2,0,1,2,3,0,1,1,13
Федоров Ф.Ф.,0,0,0,0,1,1,0,2,0,2,6
All,10,9,5,17,8,9,12,12,5,13,100

In [5]:
pd.pivot_table(appointments, index=['Специальность', 'Врач'], columns='Поставленный диагноз', 
               aggfunc = "count", values = 'Время приема', margins=True)

,Поставленный диагноз,Аллергический ринит,Ангина,Бронхит,Гастрит,Гипертония,Конъюнктивит,Мигрень,ОРВ,Остеохондроз,Сахарный диабет,All
Специальность,Врач,,,,,,,,,,,
дерматолог,Егорова Е.Е.,1.0,1.0,NaN,4.0,NaN,NaN,NaN,2.0,3.0,3.0,14
кардиолог,Петров П.П.,1.0,2.0,1.0,1.0,NaN,3.0,NaN,NaN,NaN,NaN,8
лор,Кузнецов К.К.,NaN,NaN,NaN,3.0,1.0,NaN,5.0,2.0,NaN,1.0,12
невролог,Сидорова А.А.,NaN,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,2.0,6
офтальмолог,Смирнов С.С.,3.0,NaN,2.0,NaN,1.0,2.0,3.0,NaN,1.0,1.0,13
педиатр,Васильева В.В.,2.0,2.0,1.0,2.0,1.0,NaN,NaN,2.0,1.0,NaN,11
терапевт,ванов ..,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,1.0,5
уролог,Федоров Ф.Ф.,NaN,NaN,NaN,NaN,1.0,1.0,NaN,2.0,NaN,2.0,6
хирург,Морозов М.М.,1.0,2.0,NaN,3.0,2.0,1.0,2.0,NaN,NaN,NaN,11
эндокринолог,Николаева Н.Н.,1.0,1.0,1.0,3.0,NaN,1.0,2.0,2.0,NaN,3.0,14
All,,10.0,9.0,5.0,17.0,8.0,9.0,12.0,12.0,5.0,13.0,100

### <font color='lightcoral'>3. Задача</font>
Таблица sales_dataset.csv содержит поля:
- date — дата продажи
- region — регион
- product — товар
- units — количество проданных единиц
- price — цена за единицу
1. Посчитайте, сколько раз каждый товар продавался в каждом регионе (частота транзакций). спользуйьте crosstab.
2. Постройте таблицу, где по строкам - месяц продажи, по столбцам - регионы и продукты. Продукты возьмите только Laptop и Tablet. Значения - сумма выручки. спользуйте pivot_table.

In [6]:
# Загрузка данных
df_sales = pd.read_csv("../data/sales_dataset.csv")
df_sales

          date region     product  units  price
0   2025-08-24  North     Monitor      8    201
1   2025-07-23   East      Laptop     10    482
2   2025-08-15  South      Tablet      9   1389
3   2025-08-31   West     Monitor      2   1193
4   2025-07-02   West      Laptop      3    974
..         ...    ...         ...    ...    ...
95  2025-06-16   East  Smartphone      5   1880
96  2025-09-06   East  Headphones      3   1434
97  2025-08-04   East      Tablet      8    747
98  2025-08-11   East  Headphones      3   1155
99  2025-06-25  South     Monitor      6    763

[100 rows x 5 columns]

In [8]:
display(pd.crosstab(df_sales['product'], df_sales['region']))


df_sales['date'] = pd.to_datetime(df_sales['date'])
df_sales['revenue'] = df_sales['units'] * df_sales['price']
df_sales.info()

region      East  North  South  West
product
Headphones     8      4      2     5
Laptop         7      6      8     9
Monitor        3      3      6     6
Smartphone     3      3      2     7
Tablet         8      2      4     4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     100 non-null    datetime64[ns]
 1   region   100 non-null    object
 2   product  100 non-null    object
 3   units    100 non-null    int64
 4   price    100 non-null    int64
 5   revenue  100 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 4.8+ KB

In [10]:
# Посчитайте, сколько раз каждый товар продавался в каждом регионе (частота транзакций).
pd.crosstab(df_sales['product'], df_sales['region'], aggfunc = 'sum', values = df_sales['units'],margins = True, margins_name = 'тог')

region      East  North  South  West  тог
product
Headphones    40     29     15    34   118
Laptop        45     22     53    63   183
Monitor       10     18     32    30    90
Smartphone    15     20      5    42    82
Tablet        47     12     23    17    99
тог         157    101    128   186   572

In [15]:
# Постройте таблицу, где по строкам - месяц продажи, по столбцам - регионы и продукты
# Продукты возьмите только Laptop и Tablet
# Значения - сумма выручки

pd.pivot_table(df_sales[df_sales['product'].isin(['Laptop', 'Tablet'])], index = df_sales['date'].dt.month_name(), 
               columns = ['region', 'product'], aggfunc = 'sum', values = ['revenue'])

           revenue                                                        \
region        East             North             South              West
product     Laptop   Tablet   Laptop   Tablet   Laptop   Tablet   Laptop
date
August     10584.0  12958.0    589.0      NaN  12173.0  15641.0      NaN
July       23866.0  14117.0  10034.0  19884.0      NaN   3856.0  33528.0
June        6201.0  21668.0      NaN      NaN  23510.0      NaN   8628.0
September      NaN      NaN   3232.0      NaN  22428.0    772.0  33712.0


region
product    Tablet
date
August     7376.0
July       1665.0
June       9008.0
September     NaN

### <font color='lightcoral'>6. Основы работы с Jupyter Notebook</font>

<b> Типы ячеек jupyter-ноутбука </b>
- code
- markdown
- raw

<a href="https://www.markdownguide.org/cheat-sheet/" title="Markdown cheet sheet">Markdown</a>

<b> Command mode </b>
- Ctrl + Shift + H

<b> Edit mode - режим редактирования </b>
- Shift + Tab — показать описание функции, курсор должен стоять сразу после открывающей скобки;
- Ctrl + / — закомментировать строку;
- Ctrl + Home — перейти к началу ячейки;
- Ctrl + End — перейти к концу ячейки;
- Ctrl + Shift + - — разбить ячейку по текущей строке;
- Shift + ↑↓ — выделить ячейку выше/ниже текущей;
- Ctrl + Enter — запустить выделенные ячейки;
- Shift + Enter — запустить ячейку и перейти на одну ниже, что удобно, когда последовательно запускаете сразу много.

### <font color='lightcoral'>5. Магия Jupyter</font>
- % (line) - относятся к одной строке
- %% (cell) - относятся ко всей ячейке

In [8]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %code_wrap  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %mamba  %matplotlib  %micromamba  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %uv  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%code_wrap  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3  %%ruby  %%script  %%sh  %%svg  %%sx  %%system  %%time  %%timeit  %%writefile

Automagic is ON, % prefix IS NOT needed for line magics.

In [9]:
# Вызов справки
?%time

Docstring:
::

  %time [--no-raise-error]

Time execution of a Python statement or expression.

The CPU and wall clock times are printed, and the value of the
expression (if any) is returned.  Note that under Win32, system time
is always reported as 0, since it can not be measured.

This function can be used both as a line and cell magic:

- In line mode you can time a single-line statement (though multiple
  ones can be chained with using semicolons).

- In cell mode, you can time the cell body (a directly
  following statement raises an error).

This function provides very basic timing functionality. Use the timeit
magic for more control over the measurement.

.. versionchanged:: 7.3
    User variables are no longer expanded,
    the magic line is always left unmodified.

.. versionchanged:: 8.3
    The time magic now correctly propagates system-exiting exceptions
    (such as ``KeyboardInterrupt`` invoked when interrupting execution)
    rather than just printing out the exception traceback.
    The non-system-exception will still be caught as before.

Examples
--------
::

  In [1]: %time 2**128
  CPU times: user 0.00 s, sys: 0.00 s, total: 0.00 s
  Wall time: 0.00
  Out[1]: 340282366920938463463374607431768211456L

  In [2]: n = 1000000

  In [3]: %time sum(range(n))
  CPU times: user 1.20 s, sys: 0.05 s, total: 1.25 s
  Wall time: 1.37
  Out[3]: 499999500000L

  In [4]: %time print('hello world')
  hello world
  CPU times: user 0.00 s, sys: 0.00 s, total: 0.00 s
  Wall time: 0.00

.. note::
    The time needed by Python to compile the given expression will be
    reported if it is more than 0.1s.

    In the example below, the actual exponentiation is done by Python
    at compilation time, so while the expression can take a noticeable
    amount of time to compute, that time is purely due to the
    compilation::

        In [5]: %time 3**9999;
        CPU times: user 0.00 s, sys: 0.00 s, total: 0.00 s
        Wall time: 0.00 s

        In [6]: %time 3**999999;
        CPU times: user 0.00 s, sys: 0.00 s, total: 0.00 s
        Wall time: 0.00 s
        Compiler : 0.78 s

options:
  --no-raise-error  If given, don't re-raise exceptions
File:      c:\users\vitaliy\appdata\local\programs\python\python313\lib\site-packages\ipython\core\magics\execution.py

In [10]:
?range

Init signature: range(self, /, *args, **kwargs)
Docstring:
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).
Type:           type
Subclasses:

##### <font color='lightcoral'>5.1.  %time, %timeit, %%time</font>

In [11]:
# Функция, генерирующая случайное число и засыпающая на 1 секунду, если число нечетное
import time
import numpy as np

def sleep_if_odd():
    rvs = np.random.randint(low=0, high=int(1e9))
    randbit = rvs % 2
    if randbit % 2 == 1:
        time.sleep(1)

In [12]:
%time sleep_if_odd()

CPU times: total: 0 ns
Wall time: 1 s

<b> CPU times </b>
Это время, которое процессор реально потратил на выполнение кода.
- user — время, затраченное пользовательским кодом (Python-кодом).
- sys — время, затраченное системными вызовами (например, работа с файлами, памятью, ввод/вывод).
- total — сумма user + sys.

<b> Wall time </b>
Это реальное прошедшее время по часам (как будто засекли секундомером).

Отличие: wall time может быть чуть больше CPU total, если процесс ждал чего-то (например, доступа к памяти или ОС переключала задачи).

<b>Синтаксис %timeit [-n<N> -r<R>]</b>
- n - Выполнить заданный код N раз в цикле. Если значение N не указано, оно определяется автоматически, обеспечивая достаточную точность.
- r - Количество повторений R, каждое из которых состоит из N циклов, и вычисляется средний результат. По умолчанию: 7.

In [13]:
%timeit -n 10 -r 10 sleep_if_odd()

460 ms В± 163 ms per loop (mean В± std. dev. of 10 runs, 10 loops each)

<b>%%writefile, %pycat</b><br>
Эти функции позволяют вам сохранить ячейку с кодом в питоновский файл и вывести его содержимое с подсветкой синтаксиса.

In [14]:
%%writefile test.py
print("Hello, World!")

Writing test.py

In [15]:
%pycat test.py

print("Hello, World!")

<b>%system, %%bash</b><br>
Позволяет выполнять системные команды так, будто вы работаете в терминале.

In [16]:
%system date

['’ҐЄгй\xa0п ¤\xa0в\xa0: 14.04.2026 ', '‚ўҐ¤ЁвҐ \xad®ўго ¤\xa0вг (¤¤-¬¬-ЈЈ): ']

In [17]:
%%bash
date

Couldn't find program: 'bash'

### <font color='lightcoral'>6. Решение задач</font>

1. У вас есть датафрейм с информацией о покупках различных товаров разными клиентами. Кроме того, у вас есть информация о поле каждого клиента и категории товаров. Необходимо создать сводную таблицу, чтобы проанализировать, какие категории товаров покупаются чаще всего мужчинами и женщинами разных возрастных групп.

In [86]:
# Генерация данных
data = {
    'CustomerID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Age': [25, 35, 45, 55, 25, 35, 45, 55],
    'Gender': ['M', 'M', 'M', 'M', 'F', 'F', 'F', 'F'],
    'Category': ['Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion']
}

In [89]:
# Решение
df_data = pd.DataFrame(data)
df_data

   CustomerID  Age Gender     Category
0           1   25      M  Electronics
1           2   35      M      Fashion
2           3   45      M  Electronics
3           4   55      M      Fashion
4           5   25      F  Electronics
5           6   35      F      Fashion
6           7   45      F  Electronics
7           8   55      F      Fashion

In [99]:
pd.pivot_table(df_data, index = [df_data['Category'], df_data['Age']], columns = df_data['Gender'], 
                aggfunc = 'count', values = 'CustomerID', fill_value = 0)

Gender           F  M
Category    Age
Electronics 25   1  1
            45   1  1
Fashion     35   1  1
            55   1  1

2. У вас есть датафрейм с результатами опроса, в котором каждый респондент указал свой пол и предпочтения по категориям товаров. Необходимо создать таблицу сопряженности и добавить в нее процентные значения по строкам или столбцам. спользуйте функцию div.

In [20]:
# Генерация данных
data = {
    'Gender': ['Male', 'Female', 'Male', 'Male', 'Female', 'Female'],
    'Category': ['Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion']
}
data

{'Gender': ['Male', 'Female', 'Male', 'Male', 'Female', 'Female'],
 'Category': ['Electronics',
  'Fashion',
  'Electronics',
  'Fashion',
  'Electronics',
  'Fashion']}

In [21]:
# Решение