In [2]:
import plotly.express as px
import pandas as pd

In [9]:
# Задание 1: Расширенная диаграмма рассеяния

# Создать диаграмму рассеивания с дополнительной сложностью для визуализации взаимосвязи между двумя переменными. 
# Используйте набор данных tips, доступный в Plotly Express. Постройте график total_bill на оси x и tip на оси y. 
# Раскрасьте точки по времени (обед или ужин). Добавьте на график линию тренда и настройте размер маркеров в зависимости от размера вечеринки.

df_tips = px.data.tips()
display(df_tips)
fig = px.scatter(df_tips, 
                x='total_bill',
                y='tip',
                color='time',
                trendline='ols',
                size='size',
                width=1000,
                height=600,
                title='Scatter Plot of Total Bill vs Tip Colored by Time')
fig.show()

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
# Задача 2: Создать гистограмму с расширенными возможностями настройки. Используйте набор данных tips. 
# Создайте гистограмму для total_bill. Установите число бинов на 20 и цвет по времени.
fig = px.histogram(df_tips,
                x='total_bill', 
                nbins=20,
                color='time',
                text_auto=True,
                title='Histogram of Total Bill with 20 Bins Colored by Time',)
fig.update_traces(marker=dict(line=dict(color='black', width=1)))

fig.show()

In [11]:
# Задача 3: Создайте линейный график с несколькими линиями для сравнения тенденций. Используйте набор данных gapminder, доступный в Plotly Express. 
# Отметьте год на оси x и gdpPercap на оси y. Отфильтруйте данные, чтобы включить в них только страны "Канада" и "Германия". 
# Используйте разные стили линий для каждой страны.
df_gapminder = px.data.gapminder()
display(df_gapminder)
fig = px.line(df_gapminder[df_gapminder['country'].isin(['Canada', 'Germany'])],
            x='year',
            y='gdpPercap',
            color='country',
            line_dash='country',
            markers=True,
            # text='gdpPercap',
             width=1000,
             height=600,
            title='Line Plot of GDP Per Capita Over Time for Canada and Germany with Different Line Styles')
fig.show()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [12]:
# Задача 4: Создать тепловую карту для визуализации корреляции между несколькими переменными с помощью интерактивных функций. 
# Используйте набор данных iris, доступный в Plotly Express. Рассчитайте корреляционную матрицу и визуализируйте ее с помощью тепловой карты. 
# Добавьте наведенную информацию, показывающую значения корреляции.
df_iris = px.data.iris()
display(df_iris)
correlation_matrix = df_iris.corr(numeric_only=True)

fig = px.imshow(correlation_matrix,
                text_auto=True,
                title='Correlation Heatmap of Iris Dataset',
                width=800,
                height=600,
                color_continuous_scale='RdBu_r',
                zmin=-1, zmax=1
                )
fig.show()

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3