# <b><font color='teal'>Homework 18</font></b>

In [2]:
# Импорт библиотек
import seaborn as sns
import pandas as pd
import scipy.stats as stats
from statsmodels.stats.weightstats import ztest

##### <b><font color='teal'>Задание 1</font></b>
С помощью библиотеки scipy.stats выполните независимый t-тест на наборе данных tips из seaborn. Сравните средний общий счет между курящими и некурящими.
* Если в условии задачи не сказано про равенство дисперсий, то лучше предполагать, что дисперсии НЕ равны

In [15]:
# Загрузите набор данных tips в датафрейм df_tips
df_tips = sns.load_dataset('tips')
display(df_tips.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
# В объект типа Series s_no_smoker запишите данные по общему счету для некурящих клиентов
s_no_smoker = df_tips[df_tips['smoker'] == 'No']['total_bill']

In [5]:
# В объект типа Series s_smoker запишите данные по общему счету для курящих клиентов
s_smoker = df_tips[df_tips['smoker'] == 'Yes']['total_bill']

# Сформулируйте гипотезы
H0: средний общий счет у курящих и некурящих одинаков.
H1: средний общий счет у курящих и некурящих различается.

In [19]:
# Рассчитайте двухвыборочный t-тест с НЕ равной дисперсией
# (Синтаксис в файле "Проверка гипотез" - п. 1.3.)
t_stat_1, p_value_1 = stats.ttest_ind(s_no_smoker, s_smoker, equal_var=False)

In [26]:
# Выведите результат с интерпретацией
print(f't-statistic: {t_stat_1:.4f}')
print(f'p-value: {p_value_1:.6f}')
if p_value_1 < 0.05:
    print('H0 отклоняем. Принимаем H1: средний общий счет у курящих и некурящих различается.')
else:
    print('H0 принимаем: средний общий счет у курящих и некурящих одинаков.')

t-statistic: -1.2843
p-value: 0.200805
H0 принимаем: средний общий счет у курящих и некурящих одинаков.

##### <b><font color='teal'>Задание 2</font></b>
С помощью библиотеки statsmodels выполните одновыборочный z-тест для набора данных по бриллиантам из seaborn. Проверьте, значительно ли отличается средняя цена бриллиантов от $4000.

In [25]:
# Загрузите в датафрейм df_diamonds набор данных diamonds из библиотеки seaborn
df_diamonds = sns.load_dataset('diamonds')
display(df_diamonds.head())

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [9]:
# В переменную mu запишите ожидаемое значение цены бриллиантов
mu = 4000

In [10]:
# В объект типа Series diamonds_prices запишите данные о ценах бриллиантов
diamonds_prices = df_diamonds['price']

# Сформулируйте гипотезы
H0: средняя цена бриллиантов равна 4000.
H1: средняя цена бриллиантов отличается от 4000.

In [21]:
# Рассчитайте одновыборочный z-тест 
# На уроке мы рассчитывали вручную, потому что у нас были уже рассчитанные значения
# Здесь нам дается выборка целиком, поэтому используем z_test с параметрами:
# x1 - объект Series с ценами бриллиантов
# value - ожидаемое значение цены
z_stat_2, p_value_2 = ztest(x1=diamonds_prices, value=mu)

In [27]:
# Выведите результат с интерпретацией
print(f'z-statistic: {z_stat_2:.4f}')
print(f'p-value: {p_value_2:.6f}')
if p_value_2 < 0.05:
    print('H0 отклоняем. Принимаем H1: средняя цена бриллиантов отличается от 4000.')
else:
    print('H0 принимаем: средняя цена бриллиантов равна 4000.')

z-statistic: -3.9121
p-value: 0.000091
H0 отклоняем. Принимаем H1: средняя цена бриллиантов отличается от 4000.

##### <b><font color='teal'>Задание 3</font></b>
Используйте библиотеку scipy.stats для расчета коэффициента корреляции Пирсона между total_bill и tip в наборе данных tips.

In [30]:
# Рассчитайте коэффициент корреляции Пирсона для переменных total_bill и tip в датафрейме df_tips
# (Синтаксис в файле "Основы корреляции" - п. 1)
corr_coef_3, p_value_3 = stats.pearsonr(df_tips['total_bill'], df_tips['tip'])

In [32]:
# Выведите и интерпретируйте результат:
# 1. На основании p-value определите, можно ли доверять высчитанному коэффициенту
# 2. Если ответ на предыдущий вопрос - да, то какова сила и направленность корреляции между этими двумя переменными
print(f'Pearson correlation: {corr_coef_3:.4f}')
print(f'p-value: {p_value_3}')

if p_value_3 < 0.05:
    print('Коэффициент статистически значим, ему можно доверять.')
    if abs(corr_coef_3) < 0.3:
        strength = 'слабая'
    elif abs(corr_coef_3) < 0.7:
        strength = 'умеренная'
    else:
        strength = 'сильная'
    direction = 'положительная' if corr_coef_3 > 0 else 'отрицательная'
    print(f'Сила корреляции: {strength}. Направленность: {direction}.')
else:
    print('Коэффициент статистически незначим, делать вывод о силе и направленности нельзя.')

Pearson correlation: 0.6757
p-value: 6.6924706468631854e-34
Коэффициент статистически значим, ему можно доверять.
Сила корреляции: умеренная. Направленность: положительная.